test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ok
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... ok

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, -6760.408440973835, 3[197 chars]085)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, -6760.408440973835, 398864.59155902616)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, -6760.408440973835, 398864.59155902616),
-  (-229.1831180523293, 13521.81688194767, -797787.1831180523),
-  (286.4788975654116, -16901.521102434588, 997190.4788975654),
-  (234.3397382085067, -13825.660261791494, 815714.3397382085)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

----------------------------------------------------------------------
Ran 7 tests in 0.006s

FAILED (failures=1)
